<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use App\Models\Medication;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        $medications = [
            // Citalopram
            [
                'name' => 'Citalopram',
                'generic_name' => 'Citalopram',
                'drug_class' => 'Selective Serotonin Reuptake Inhibitors (SSRIs)',
                'description' => 'Used to treat depression and anxiety disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '10mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.30,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 1
            ],
            [
                'name' => 'Citalopram',
                'generic_name' => 'Citalopram',
                'drug_class' => 'Selective Serotonin Reuptake Inhibitors (SSRIs)',
                'description' => 'Used to treat depression and anxiety disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '20mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.40,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => true,
                'order' => 2
            ],
            [
                'name' => 'Citalopram',
                'generic_name' => 'Citalopram',
                'drug_class' => 'Selective Serotonin Reuptake Inhibitors (SSRIs)',
                'description' => 'Used to treat depression and anxiety disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '40mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.50,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 3
            ],
            [
                'name' => 'Citalopram',
                'generic_name' => 'Citalopram',
                'drug_class' => 'Selective Serotonin Reuptake Inhibitors (SSRIs)',
                'description' => 'Used to treat depression and anxiety disorders.',
                'dosage_form' => 'Solution',
                'route_of_administration' => 'Oral',
                'strength' => '10mg/5mL',
                'manufacturer' => 'Various',
                'unit_price' => 10.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 4
            ],

            // Clobetasol
            [
                'name' => 'Clobetasol',
                'generic_name' => 'Clobetasol',
                'drug_class' => 'Corticosteroids',
                'description' => 'Used to treat various skin conditions such as eczema, psoriasis, and dermatitis.',
                'dosage_form' => 'Cream',
                'route_of_administration' => 'Topical',
                'strength' => '0.05%',
                'manufacturer' => 'Various',
                'unit_price' => 15.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => true,
                'order' => 1
            ],
            [
                'name' => 'Clobetasol',
                'generic_name' => 'Clobetasol',
                'drug_class' => 'Corticosteroids',
                'description' => 'Used to treat various skin conditions such as eczema, psoriasis, and dermatitis.',
                'dosage_form' => 'Ointment',
                'route_of_administration' => 'Topical',
                'strength' => '0.05%',
                'manufacturer' => 'Various',
                'unit_price' => 15.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 2
            ],
            [
                'name' => 'Clobetasol',
                'generic_name' => 'Clobetasol',
                'drug_class' => 'Corticosteroids',
                'description' => 'Used to treat various skin conditions such as eczema, psoriasis, and dermatitis.',
                'dosage_form' => 'Solution',
                'route_of_administration' => 'Topical',
                'strength' => '0.05%',
                'manufacturer' => 'Various',
                'unit_price' => 20.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 3
            ],
            [
                'name' => 'Clobetasol',
                'generic_name' => 'Clobetasol',
                'drug_class' => 'Corticosteroids',
                'description' => 'Used to treat various skin conditions such as eczema, psoriasis, and dermatitis.',
                'dosage_form' => 'Foam',
                'route_of_administration' => 'Topical',
                'strength' => '0.05%',
                'manufacturer' => 'Various',
                'unit_price' => 25.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 4
            ],
            [
                'name' => 'Clobetasol',
                'generic_name' => 'Clobetasol',
                'drug_class' => 'Corticosteroids',
                'description' => 'Used to treat various skin conditions such as eczema, psoriasis, and dermatitis.',
                'dosage_form' => 'Shampoo',
                'route_of_administration' => 'Topical',
                'strength' => '0.05%',
                'manufacturer' => 'Various',
                'unit_price' => 30.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 5
            ],

            // Clonidine
            [
                'name' => 'Clonidine',
                'generic_name' => 'Clonidine',
                'drug_class' => 'Alpha-2 Adrenergic Agonists',
                'description' => 'Used to treat high blood pressure, ADHD, anxiety, and certain pain conditions.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '0.1mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.25,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => true,
                'order' => 1
            ],
            [
                'name' => 'Clonidine',
                'generic_name' => 'Clonidine',
                'drug_class' => 'Alpha-2 Adrenergic Agonists',
                'description' => 'Used to treat high blood pressure, ADHD, anxiety, and certain pain conditions.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '0.2mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.30,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 2
            ],
            [
                'name' => 'Clonidine',
                'generic_name' => 'Clonidine',
                'drug_class' => 'Alpha-2 Adrenergic Agonists',
                'description' => 'Used to treat high blood pressure, ADHD, anxiety, and certain pain conditions.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '0.3mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.35,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 3
            ],
            [
                'name' => 'Clonidine',
                'generic_name' => 'Clonidine',
                'drug_class' => 'Alpha-2 Adrenergic Agonists',
                'description' => 'Used to treat high blood pressure, ADHD, anxiety, and certain pain conditions.',
                'dosage_form' => 'Patch',
                'route_of_administration' => 'Transdermal',
                'strength' => '0.1mg/24hr',
                'manufacturer' => 'Various',
                'unit_price' => 10.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 4
            ],
            [
                'name' => 'Clonidine',
                'generic_name' => 'Clonidine',
                'drug_class' => 'Alpha-2 Adrenergic Agonists',
                'description' => 'Used to treat high blood pressure, ADHD, anxiety, and certain pain conditions.',
                'dosage_form' => 'Patch',
                'route_of_administration' => 'Transdermal',
                'strength' => '0.2mg/24hr',
                'manufacturer' => 'Various',
                'unit_price' => 12.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 5
            ],
            [
                'name' => 'Clonidine',
                'generic_name' => 'Clonidine',
                'drug_class' => 'Alpha-2 Adrenergic Agonists',
                'description' => 'Used to treat high blood pressure, ADHD, anxiety, and certain pain conditions.',
                'dosage_form' => 'Patch',
                'route_of_administration' => 'Transdermal',
                'strength' => '0.3mg/24hr',
                'manufacturer' => 'Various',
                'unit_price' => 15.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 6
            ],

            // Dantrolene
            [
                'name' => 'Dantrolene',
                'generic_name' => 'Dantrolene',
                'drug_class' => 'Direct-Acting Skeletal Muscle Relaxants',
                'description' => 'Used to treat muscle spasticity and malignant hyperthermia.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '25mg',
                'manufacturer' => 'Various',
                'unit_price' => 2.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 1
            ],
            [
                'name' => 'Dantrolene',
                'generic_name' => 'Dantrolene',
                'drug_class' => 'Direct-Acting Skeletal Muscle Relaxants',
                'description' => 'Used to treat muscle spasticity and malignant hyperthermia.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '50mg',
                'manufacturer' => 'Various',
                'unit_price' => 3.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => true,
                'order' => 2
            ],
            [
                'name' => 'Dantrolene',
                'generic_name' => 'Dantrolene',
                'drug_class' => 'Direct-Acting Skeletal Muscle Relaxants',
                'description' => 'Used to treat muscle spasticity and malignant hyperthermia.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '100mg',
                'manufacturer' => 'Various',
                'unit_price' => 4.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 3
            ],
            [
                'name' => 'Dantrolene',
                'generic_name' => 'Dantrolene',
                'drug_class' => 'Direct-Acting Skeletal Muscle Relaxants',
                'description' => 'Used to treat malignant hyperthermia and other conditions that cause severe muscle rigidity.',
                'dosage_form' => 'Injection',
                'route_of_administration' => 'Intravenous',
                'strength' => '20mg',
                'manufacturer' => 'Various',
                'unit_price' => 50.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 4
            ],

            // Diltiazem
            [
                'name' => 'Diltiazem',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '30mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.30,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 1
            ],
            [
                'name' => 'Diltiazem',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '60mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.40,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => true,
                'order' => 2
            ],
            [
                'name' => 'Diltiazem',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '90mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.50,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 3
            ],
            [
                'name' => 'Diltiazem',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Tablet',
                'route_of_administration' => 'Oral',
                'strength' => '120mg',
                'manufacturer' => 'Various',
                'unit_price' => 0.60,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 4
            ],
            [
                'name' => 'Diltiazem ER',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Extended-release formulation used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '120mg',
                'manufacturer' => 'Various',
                'unit_price' => 1.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 5
            ],
            [
                'name' => 'Diltiazem ER',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Extended-release formulation used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '180mg',
                'manufacturer' => 'Various',
                'unit_price' => 1.25,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 6
            ],
            [
                'name' => 'Diltiazem ER',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Extended-release formulation used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '240mg',
                'manufacturer' => 'Various',
                'unit_price' => 1.50,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 7
            ],
            [
                'name' => 'Diltiazem ER',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Extended-release formulation used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '300mg',
                'manufacturer' => 'Various',
                'unit_price' => 1.75,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 8
            ],
            [
                'name' => 'Diltiazem ER',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Extended-release formulation used to treat high blood pressure, angina, and certain heart rhythm disorders.',
                'dosage_form' => 'Capsule',
                'route_of_administration' => 'Oral',
                'strength' => '360mg',
                'manufacturer' => 'Various',
                'unit_price' => 2.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 9
            ],
            [
                'name' => 'Diltiazem',
                'generic_name' => 'Diltiazem',
                'drug_class' => 'Calcium Channel Blockers',
                'description' => 'Used to treat certain heart rhythm disorders and acute hypertension.',
                'dosage_form' => 'Injection',
                'route_of_administration' => 'Intravenous',
                'strength' => '5mg/mL',
                'manufacturer' => 'Various',
                'unit_price' => 20.00,
                'requires_prescription' => true,
                'controlled_substance' => false,
                'storage_conditions' => 'Store at room temperature away from light and moisture.',
                'status' => 'approved',
                'is_usual_dosage' => false,
                'order' => 10
            ]
        ];

        foreach ($medications as $medication) {
            Medication::create($medication);
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        $genericNames = [
            'Citalopram',
            'Clobetasol',
            'Clonidine',
            'Dantrolene',
            'Diltiazem'
        ];

        foreach ($genericNames as $genericName) {
            Medication::where('generic_name', $genericName)->delete();
        }
    }
};
